// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/actualites/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/actualites/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/actualites/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/actualites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/actualites">> = Specific
  const handler = {} as typeof import("../../../src/app/actualites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/concessionnaires/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/concessionnaires/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/concessionnaires/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/concessionnaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/concessionnaires">> = Specific
  const handler = {} as typeof import("../../../src/app/concessionnaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/connexion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connexion">> = Specific
  const handler = {} as typeof import("../../../src/app/connexion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/estimation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estimation">> = Specific
  const handler = {} as typeof import("../../../src/app/estimation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inscription">> = Specific
  const handler = {} as typeof import("../../../src/app/inscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/marques/[brand]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marques/[brand]">> = Specific
  const handler = {} as typeof import("../../../src/app/marques/[brand]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/occasions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/occasions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/occasions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/occasions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/occasions">> = Specific
  const handler = {} as typeof import("../../../src/app/occasions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/publier-annonce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publier-annonce">> = Specific
  const handler = {} as typeof import("../../../src/app/publier-annonce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/voitures-neuves/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voitures-neuves">> = Specific
  const handler = {} as typeof import("../../../src/app/voitures-neuves/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
